name: Validate JSON

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install ajv-cli
        run: npm install -g ajv-cli

      - name: Validate Baseball JSON files
        run: |
          ajv validate \
            -s ./schema.json \
            -d "baseball/**/*.json" \
            --all-errors \
            --verbose

      - name: Validate Football JSON files
        run: |
          ajv validate \
            -s ./schema.json \
            -d "football/**/*.json" \
            --all-errors \
            --verbose

      - name: Validate Basketball JSON files
        run: |
          ajv validate \
            -s ./schema.json \
            -d "basketball/**/*.json" \
            --all-errors \
            --verbose

      - name: Validate Hockey JSON files\
        run: |
          ajv validate \
            -s ./schema.json \
            -d "hockey/**/*.json" \
            --all-errors \
            --verbose