name: Validate JSON

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install ajv-cli
        run: npm install -g ajv-cli ajv-formats

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Validate Baseball JSON files
        run: |
          ajv validate \
            -c ajv-formats \
            -s ./schemas/release.json \
            -d "categories/baseball/**/*.json" \
            --all-errors \
            --verbose

      - name: Validation Baseball Attribute Tags
        run: python scripts/validate-json-data.py "../categories/baseball/**/*.json"

      - name: Validate Football JSON files
        run: |
          ajv validate \
            -c ajv-formats \
            -s ./schemas/release.json \
            -d "categories/football/**/*.json" \
            --all-errors \
            --verbose
      - name: Validation Football Attribute Tags
        run: python scripts/validate-json-data.py "../categories/football/**/*.json"

      - name: Validate Basketball JSON files
        run: |
          ajv validate \
            -c ajv-formats \
            -s ./schemas/release.json \
            -d "categories/basketball/**/*.json" \
            --all-errors \
            --verbose

      - name: Validation Basketball Attribute Tags
        run: python scripts/validate-json-data.py "../categories/basketball/**/*.json"

      - name: Validate Hockey JSON files
        run: |
          ajv validate \
            -c ajv-formats \
            -s ./schemas/release.json \
            -d "categories/hockey/**/*.json" \
            --all-errors \
            --verbose

      - name: Validation Hockey Attribute Tags
        run: python scripts/validate-json-data.py "../categories/hockey/**/*.json"

